[package]
name = "test-utils"
version = { workspace = true }
edition = "2021"

[dependencies]

# External dependencies.
async-trait = "0.1.80"
ethers = "2.0.8"
eyre = "0.6.8"
futures-locks = "0.7.1"
lazy_static = "1.4.0"
thiserror = "1.0"
