[package]
name = "fixed-point"
version = {workspace=true}
edition = "2021"

[dependencies]

# External dependencies
ethers = "2.0.8"
eyre = "0.6.8"
rand = "0.8.5"

[dev-dependencies]
tokio = { version = "1", features = ["full"] }

# Workspace dependencies
test-utils = { path = "../test-utils" }
