name: Rust Lint

on:
  push:
    branches:
      - main
  pull_request:
  merge_group:

jobs:
  # Check if files in the /contracts, /test, /crates, or /lib directories or the
  # /foundry.toml, /Cargo.lock, or /Cargo.toml files were changed in this PR.
  detect-changes:
    uses: ./.github/workflows/check_diff.yml
    with:
      pattern: ^crates/\|^Cargo\.lock$\|^Cargo\.toml$\|^rustfmt\.toml$\|^\.github/workflows/rust_lint\.yml$

  lint:
    name: rust lint
    runs-on: ubuntu-latest
    needs: detect-changes
    if: needs.detect-changes.outputs.changed == 'true'
    steps:
      - name: Checkout hyperdrive-rs
        uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.GITHUB_TOKEN }}

      # NOTE: This is needed to ensure that hyperdrive-wrappers builds correctly.
      - name: Install foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Fetch latest release tag from Hyperdrive
        run: ./scripts/fetch-latest-tag.sh delvtech hyperdrive
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          components: rustfmt, clippy

      - name: lint
        run: make lint
        env:
          HYPERDRIVE_REPO_URL: https://github.com/delvtech/hyperdrive.git
          HYPERDRIVE_REF: ${{ env.latest_tag_hyperdrive }}
