name: Rust Lint

on:
  push:
  pull_request:
  merge_group:

jobs:
  detect-changes:
    uses: ./.github/workflows/check_diff.yaml
    with:
      pattern: ^crates/\|^Cargo\.lock$\|^Cargo\.toml$\|^rustfmt\.toml$\|^\.github/workflows/rust_lint\.yml$

  lint:
    name: rust lint
    runs-on: ubuntu-latest
    needs: detect-changes
    if: needs.detect-changes.outputs.changed == 'true'
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          token: ${{ secrets.GITHUB_TOKEN }}

      # NOTE: This is needed to ensure that hyperdrive-wrappers builds correctly.
      - name: install foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: check out hyperdrive
        uses: actions/checkout@v4
        with:
          repository: delvtech/hyperdrive
          path: "./hyperdrive"

      - name: build hyperdrive
        run: cd hyperdrive && make build-sol

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          components: rustfmt, clippy

      - name: lint
        run: make lint
