name: Rust Test

on:
  push:
    branches:
      - main
  pull_request:
  merge_group:

jobs:
  # Check if files in the /contracts, /test, /crates, or /lib directories or the
  # /foundry.toml, /Cargo.lock, or /Cargo.toml files were changed in this PR.
  detect-changes:
    uses: ./.github/workflows/check_diff.yml
    with:
      pattern: ^contracts/\|^test/\|^crates/\|^lib/\|^foundry\.toml$\|^Cargo\.lock$\|^Cargo\.toml$\|^\.github/workflows/rust_test\.yml$

  test:
    name: rust test
    runs-on: ubuntu-latest
    needs: detect-changes
    if: needs.detect-changes.outputs.changed == 'true'
    steps:
      - name: Checkout hyperdrive-rs
        uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.GITHUB_TOKEN }}

      # NOTE: This is needed to ensure that hyperdrive-wrappers builds correctly.
      - name: install foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          components: rustfmt, clippy

      - name: Get list of tests from main branch
        run: |
          git checkout main
          ./list_tests.sh > main_tests.txt

      - name: Get list of tests from pull request branch
        run: |
          git checkout ${{ github.head_ref }}
          ./list_tests.sh > pr_tests.txt

      - name: Compare test lists and run new tests
        run: |
          new_tests=$(comm -13 main_tests.txt pr_tests.txt)
          if [ -n "$new_tests" ]; then
            echo "New tests found:"
            echo "$new_tests"
            echo "$new_tests" | while read test; do
              echo "Running test: $test"
              HYPERDRIVE_FUZZ_RUNS=1000 HYPERDRIVE_FAST_FUZZ_RUNS=100000 cargo test $test --
            done
          else
            echo "No new tests found."
          fi

      - name: test
        run: make test
