name: rust test

on:
  push:
    branches:
      - main
  pull_request:
  merge_group:

jobs:
  # Check if files in the /test, /crates, or /lib directories or the
  # /Cargo.lock, or /Cargo.toml files were changed in this PR.
  detect-changes:
    uses: ./.github/workflows/check_diff.yml
    with:
      pattern: ^test/\|^crates/\|^lib/\|^target/\|^Cargo\.lock$\|^Cargo\.toml$\|^\.github/workflows/rust_test\.yml$

  test:
    name: rust test
    runs-on: ubuntu-latest-8core
    needs: detect-changes
    if: needs.detect-changes.outputs.changed == 'true'
    steps:
      - name: Checkout hyperdrive-rs
        uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.GITHUB_TOKEN }}

      # NOTE: This is needed to ensure that hyperdrive-wrappers builds correctly.
      - name: install foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          components: rustfmt, clippy

      - name: test
        run: make test
